const num1= 6.2 ;
const num2 = 10 ;
let multiply = num1 * num2;
console.log( multiply);
let random = Math.floor(Math.random() * 100);
console.log( random);
const num3 = 68;
const num4 = 8;
let mod = num3 % num4;
console.log( mod);
let max = Math.max(1,2,3,4,15,17,20);
console.log( max);